apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiops-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aiops
  template:
    metadata:
      labels:
        app: aiops
    spec:
      containers:
        - name: aiops
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aiops-secrets
                  key: slackToken
            - name: JIRA_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aiops-secrets
                  key: jiraToken
            - name: GITHUB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aiops-secrets
                  key: githubToken
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: aiops-secrets
                  key: openaiApiKey
