replicaCount: 1

image:
  repository: your-docker-repo/aiops
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: aiops.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

secrets:
  slackToken: your-slack-token
  jiraToken: your-jira-token
  githubToken: your-github-token
  openaiApiKey: your-openai-api-key
